### ISSUE TITLE
Update for Oculus Rift API/runtime 1.4+

### ISSUE THREAD

**Issue by cmbruns** [cmbruns/pyovr#16]
I cannot install the latest Oculus Runtime on my development computer because my CPU is too old. So I won't be able to update this project for a while. Sorry.

Workaround: Get an HTC Vive, and try https://github.com/cmbruns/pyopenvr
It's better anyway.

**Comment by cmbruns** [comment]
I built a new computer, so now I should be able to advance pyovr to more recent Oculus versions, if I find the time.

**Comment by thirteen-io** [comment]
Glad to hear this, Do you have any ETA or is it "when it's done"?

Many thanks!

**Comment by cmbruns** [comment]
@thirteen-io it's done just now.
Updated for SDK 1.6 in revision 6857d2ee84b6978fe002b9e2fcda5a7117944384
