### ISSUE TITLE
Update for Python 3

### ISSUE THREAD

**Issue by cmbruns** [cmbruns/pyovr#17]
It wasn't so hard in pyopenvr, so it's probably not too hard here in pyovr.
But are there any actual users of pyovr? I'm not sure...

**Comment by Xeyler** [comment]
Python 3 support would be great!

I'm just one person, but I could definitely use it.

**Comment by cmbruns** [comment]
@Xeyler One helpful thing just one person could do, would be to try using pyovr with python 3, and post whatever error messages you see here in this thread. Doing that would do two things: 1) provide a starting point for finding what needs fixing, and 2) show that someone other than me is willing to put some effort into this task.

**Comment by Xeyler** [comment]
Alright, I have verified that the [example given in the README](https://github.com/cmbruns/pyovr/blob/master/README.md#use) works with Python 2.7(64 bit), outputting the pose of the headset.

I run into issues when trying to import the wrapper into Python 3.6.1(also 64 bit), though:
```
>>> import ovr
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Xeyler\AppData\Local\Programs\Python\Python36\lib\site-packages\ovr\__init__.py", line 5, in <module>
    from _ovr1130 import *
ModuleNotFoundError: No module named '_ovr1130'
```

## Notes:
The '_ovr1130' module is the first and only module called by init... Indeed, I have verified that '_ovr1130.py' is included with 'init.py' in the site-packages/ovr folder for Python 3.6

It seems like a fairly straightforward place to start, but I'm unfamiliar with Python. Unless Python 3 imports modules in a different manner than Python 2, then this must be an issue specific to my environment.

I apologize for my inexperience with Python. I'll try my best to help with this Python 3 refactor, but let me know if there's anything more I can do along the way.

**Comment by cmbruns-hhmi** [comment]
Thanks @Xeyler for testing and posting the results here.

This particular ModuleNotFoundError is a bit surprising to me. I'm planning to install python 3 on my Rift development computer to see if I can reproduce this. Up to now, I have been developing with 32-bit python 2.7. I suppose I should use 64-bit python 3.6 to investigate this issue.

@ckbruns against what I said before, we should install 64-bit python 3.6 for this investigation.

**Comment by Xeyler** [comment]
It would seem that I'm able to overcome this issue if I append the module's folder to Python's sys.path:
```
>>> import ovr
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Xeyler\AppData\Local\Programs\Python\Python36\lib\ovr\__init__.py", line 5, in <module>
    from _ovr1130 import *
ModuleNotFoundError: No module named '_ovr1130'
>>> sys.path.append('C:\\Users\\Xeyler\\AppData\\Local\\Programs\\Python\\Python36\\Lib\\ovr')
>>> import ovr
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Xeyler\AppData\Local\Programs\Python\Python36\lib\ovr\__init__.py", line 5, in <module>
    from _ovr1130 import *
  File "C:\Users\Xeyler\AppData\Local\Programs\Python\Python36\Lib\ovr\_ovr1130.py", line 78, in <module>
    ovrFalse = c_char(chr(0)) # note potential conflict with Python built in symbols
TypeError: one character bytes, bytearray or integer expected
```
This is strange, though, because Python 2.7 doesn't require you to explicitly add the folder to the module paths. Python 2.7 does, by default, have the same paths as Python 3.6, but it also has 'lib\plat-win' and 'lib\lib-tk'. Neither of those folders would contain the ovr wrapper, though, so Python 2.7 must import modules from the lib folder differently...

Beyond the system paths, though, issues become purely syntactic.

**Comment by Xeyler** [comment]
Python 3 doesn't interpret `from _ovr1130 import *` correctly. Although, it does interpret `from ._ovr1130 import *` correctly.

It would appear that my original assessment of Python 3 importing modules differently was correct.

My [first refactor PR](https://github.com/cmbruns/pyovr/pull/20) addresses this issue among many other syntactic nuances. Although, I refactored it automatically, so there will be some other things to change.
