### ISSUE TITLE
Don't enable vsync for the glut Rift examples

### ISSUE THREAD

**Issue by jherico** [cmbruns/pyovr#3]
Your glut_renderer.py uses `glutInitDisplayMode(GLUT_RGBA | GLUT_DOUBLE)` to initialize the display.  However, using GLUT_DOUBLE enables v-sync, causing judder on the Rift display.  Disable the v-sync by initializing as `glutInitDisplayMode(GLUT_RGBA)`

**Comment by cmbruns** [comment]
Fixed by jherico in revision 076ac9427a51f68f92d2e932c227d3100deafff8
